name: Demo Workflow
on:
  push:
    branches:
      - master
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print context
        run: |
          echo "Candidate Dashboard | merged into master:"
          echo "Ticket: ${{ github.event.head_commit.message }}"
